### ISSUE TITLE
Checksum mismatch error

### ISSUE THREAD

**Issue by zseta** [vdaas/vald-client-go#9]
I'm following the get started [tutorial here](https://vald.vdaas.org/docs/tutorial/get-started/), and the last step is this:
```bash
go run main.go
```

When I run this, I get the following error:
```
go: downloading github.com/kpango/fuid v0.0.0-20221203053508-503b5ad89aa1
go: downloading gonum.org/v1/hdf5 v0.0.0-20210714002203-8c5d23bc6946
go: downloading github.com/vdaas/vald-client-go v1.7.6
go: downloading github.com/kpango/glg v1.6.15
go: downloading google.golang.org/grpc v1.56.1
verifying github.com/vdaas/vald-client-go@v1.7.6: checksum mismatch
        downloaded: h1:Clg45IgCsR7FIVARn/WNbTHCvu4FCaJWBDAQnYcCgDs=
        go.sum:     h1:rvd7Rt6Xx917r9Yy9sB4wnYCsguegXXaQUME9JquxGU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I'm not sure if this is is an issue on my end or it's the library?

**Comment by kpango** [comment]
Hi, I'm kpango from vald team.

Sorry for replying late due to the summer vacation in Japan since last week.

I apologize for the inconvenience.
The release of v1.7.6 of vald-client-go may have failed due to CI.
Since broken v1.7.6 has already been registered in gosumdb and it is impossible to remove it from gosumdb, we are planning to release vald v1.7.7 and vald-client-go v1.7.7 in the near future.

To use v1.7.6, you will need to set GOPRIVATE=github.com/vdaas/vald-client-go and resolve the go module.
